#seata配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务分组名
  tx-service-group: default_tx_group
  # 事务分组映射
  service:
    vgroupMapping:
      default_tx_group: "default"
  use-jdk-proxy: true
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      namespace: seata
      group: SEATA_GROUP
      dataId: "seataServer.properties"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      namespace: seata

#数据源公共配置
spring:
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.cj.jdbc.Driver
  # Druid StatViewServlet配置
  druid:
    stat-view-servlet:
      # 默认true 内置监控页面首页/druid/index.html
      enabled: true
      url-pattern: /druid/*
      # 允许清空统计数据
      reset-enable: true
      # IP白名单 多个逗号分隔
      allow:
      # IP黑名单
      deny:   

#mybatis-plus公共配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)  