server:
  port: 8014

# 数据源配置
spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xhcc-generator?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:      

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)       

#日志追踪
plumelog:
  appName: xunheng-generator
  redisHost: 192.168.3.100:6379
  redisAuth: 123456    
  redisDb: 3  