server:
  port: 8011


# gateway配置    
spring:
  resources:
    add-mappings: true
  cloud:
    gateway:
      routes:
        - id: system-route
          uri: lb://xunheng-system
          predicates:
            - Path=/xunheng-system/**
          filters:
            - StripPrefix=1
        - id: log-route
          uri: lb://xunheng-log
          predicates:
            - Path=/xunheng-log/**
          filters:
            - StripPrefix=1    
        - id: quartz-route
          uri: lb://xunheng-quartz
          predicates:
            - Path=/xunheng-quartz/**
          filters:
            - StripPrefix=1  
        - id: generator-route
          uri: lb://xunheng-generator
          predicates:
            - Path=/xunheng-generator/**
          filters:
            - StripPrefix=1     
        - id: file-route
          uri: lb://xunheng-file
          predicates:
            - Path=/xunheng-file/**
          filters:
            - StripPrefix=1  
        - id: chatgpt-route
          uri: lb://xunheng-chatgpt
          predicates:
            - Path=/xunheng-chatgpt/**
          filters:
            - StripPrefix=1  
        - id: chatgpt-ws
          uri: lb:ws://xunheng-chatgpt
          predicates: 
            - Path=/xunheng-chatgpt/websocket/**
          filters:
            - StripPrefix=1   
        - id: wechat-route
          uri: lb://xunheng-wechat
          predicates:
            - Path=/xunheng-wechat/**
          filters:
            - StripPrefix=1
#忽略鉴权URL
ignored:
  urls:
    - /xunheng-system/login
    - /xunheng-system/captcha/*
    - /xunheng-system/captcha/draw/*
    - /favicon.ico
    - /quartz/quartzJob/**
    - /system/dictData/getByType/**
    - /system/common/**
    - /druid/**
    - /swagger-ui/index.html
    - /v3/api-docs
    - /v3/api-docs/swagger-config
    - /v3/api-docs/**
    - /webjar/**
    - /**/swagger-ui/index.html
    - /**/v3/api-docs
    - /**/v3/api-docs/swagger-config
    - /**/v3/api-docs/**
    - /**/doc.html
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /xunheng-wechat/wma/auth

knife4j:
  gateway:
    # 是否开启
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: manual
    routes:
      - name: 后台系统服务
        service-name: xunheng-system
        url: /xunheng-system/v3/api-docs
        context-path: /xunheng-system
      - name: 代码生成服务
        service-name: xunheng-generator
        url: /xunheng-generator/v3/api-docs
        context-path: /xunheng-generator
      - name: 微信服务
        service-name: xunheng-wechat
        url: /xunheng-wechat/v3/api-docs
        context-path: /xunheng-wechat
      - name: 计划任务服务
        service-name: xunheng-quartz
        url: /xunheng-quartz/v3/api-docs
        context-path: /xunheng-quartz
      - name: 日志服务
        service-name: xunheng-log
        url: /xunheng-log/v3/api-docs
        context-path: /xunheng-log
      - name: 文件服务
        service-name: xunheng-file
        url: /xunheng-file/v3/api-docs
        context-path: /xunheng-file
      - name: chatgpt服务
        service-name: xunheng-chatgpt
        url: /xunheng-chatgpt/v3/api-docs
        context-path: /xunheng-chatgpt